### PR TITLE
Use PostCSS 7 and require Node.js 6

### PR DESCRIPTION
**Pull request by realityking**

### CODE REVIEW

**Comment by realityking** [comment]
@joscha Could you take a look at this one and #10? Thanks!

**Comment by joscha** [comment]
O, I didn't watch this repository, I missed these...so sorry, will have a look!

**Comment by joscha** [comment]
I am on mobile right now. Will need a computer to resolve the conflicting files, but gist looks good!

**Comment by realityking** [comment]
I tried rebasing but something weird is happening. While my branch is looking good (https://github.com/realityking/node-detective-postcss/commits/postcss7) the PR isn't updating.

Let's see if it sorts itself out in an hour or I'll open a new PR.

**Comment by realityking** [comment]
Now it showed up and everything is green :)

**Pull request merged**
