### PR TITLE
Remove runkitExample.js from package.json

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Review by joscha — APPROVED** [review]
I was under the impression it needed to be part of the published package - if it is enough to just expose the reference to it in the package.json without exporting it then this change LGTM. It does feel inconsistent though to reference a file that is not part of the bundle.

**Comment by XhmikosR** [comment]
@joscha wait, does it need to ship with the package? If so, then my patch is wrong.

**Comment by XhmikosR** [comment]
In package.json files section, we specify the needed files we want to ship. I was under the impression that `runkitExample.js` doesn't not need to ship with the rest of the files since it's an example.

**Comment by joscha** [comment]
I was under the impression that runkit pulls this file in when it loads the
package and constructs the example. I read up on the documentation earlier:
https://runkit.com/docs/resources#pages but it's inconclusive. I suppose
the only way to find out is to publish a pre-version and load it into
runkit and see if it still works. I do wonder how that would work though,
because how would runkit know which npm package version corresponds to what
repo state. The file doesn't hurt, it's super small.

**Comment by XhmikosR** [comment]
No worries, let's drop the patch. I thought it was a mistake.

**Pull request closed without merging**
