### PR TITLE
chore: update some of the major dependencies

### PR DESCRIPTION
**Pull request by joscha**
references https://github.com/dependents/node-detective-postcss/pull/145

### CODE REVIEW

**Comment by joscha** [comment]
CC @XhmikosR - ready to merge. ~We should probably bump the major version with this.~ might not actually be needed, as compat is not changed and the package name doesn't change. The NPM token will need to be updated however.

Actually, can you give me config rights on this repo, please? I can't see the settings any longer. Ta!

**Comment by XhmikosR** [comment]
@joscha thanks, I gave you admin rights here :)

That being said, don't merge this yet. I'll split this PR so that we can land the non-breaking changes separately. I should be able to do it later today.

**Comment by joscha** [comment]
Great! Is there a npm group for dependents?

**Comment by XhmikosR** [comment]
There is but I'd need to dig in to see if I have admin rights there :)

**Comment by XhmikosR** [comment]
@joscha I split the patches. There is an npm organization (https://www.npmjs.com/org/dependents) but I don't have admin rights, so we need @mrjoelkemp to add you/move the package there too.

**Comment by XhmikosR** [comment]
After this is merged, you can merge the other dep PRs assuming they don't break anything and release a new major version version :)

**Comment by mrjoelkemp** [comment]
@XhmikosR Made you an owner of the npm org. The UI to manage that org is so confusing on npm. Figured it out.

**Comment by joscha** [comment]
> @XhmikosR Made you an owner of the npm org. The UI to manage that org is so confusing on npm. Figured it out.

@XhmikosR are you able to produce an NPM_TOKEN and add it to the secrets in the settings of this project, please: https://github.com/dependents/node-detective-postcss/settings/secrets/actions/NPM_TOKEN ? After that I can create the new 6.0.0 release.

**Comment by XhmikosR** [comment]
@joscha @mrjoelkemp I have no idea how to move a package to the npm org :/

@mrjoelkemp can you make @joscha an admin of the detective-postcss package?

BTW the token doesn't need to change in theory.

**Comment by joscha** [comment]
I revoked all tokens after I moved the repo but didn't have admin access anymore. I can't really  leave my token in a shared public org as I can't limit the access, so I'd prefer if you created one for repo if you don't mind.

**Comment by XhmikosR** [comment]
OK, I think we need @mrjoelkemp to give you admin rights to the detective-postcss repo after it's moved to the npm org so that you can manage it independently

**Comment by joscha** [comment]
I can give access to the package to an org or user.

**Comment by XhmikosR** [comment]
BTW v5.1.0 is broken :/

```
Error: Cannot find module 'C:\Users\xmr\Desktop\detective\node-precinct\node_modules\detective-postcss\dist\index.js'. Please verify that the package.json has a valid "main" entry
```

We'll need to cut a new 5.1.1 release before 6.0.0.

**Comment by joscha** [comment]
👍

Wonder if it's worth to add a pack and require check before publishing to
avoid errors like these in the future.

**Comment by XhmikosR** [comment]
Definitely worth adding a new action to test this if you have some time later :)

**Pull request merged**
