### PR TITLE
Update npm-publish.yml

### PR DESCRIPTION
**Pull request by XhmikosR**
Specify Node.js version

### CODE REVIEW

**Comment by XhmikosR** [comment]
@joscha maybe this needs to run the prepack script too?

**Comment by joscha** [comment]
> @joscha maybe this needs to run the prepack script too?

It should implicitly during the publish already?

**Comment by XhmikosR** [comment]
Not sure if it does, which might be why 5.1.0 is broken...

I made a 5.x branch we just need to sort out the tokens and release a 5.1.1 from that branch ASAP. I'd say, better add your token for now so that we can cut a 5.1.1 and we update it later.

The npm org has only 2 people, me and @mrjoelkemp and 2FA is enabled, so it should be OK just for this :)

**Comment by joscha** [comment]
> Not sure if it does, which might be why 5.1.0 is broken...

behavior of `npm pack` is different in `npm` 6.x vs 8.x. I pushed a fix to the 5.x branch.

**Comment by joscha** [comment]
5.1.1 was released and is working.

**Pull request merged**
